version: '3.2'

services:
        db:
                image: postgres:9.6
                # volumes:
                #         - postgres_data:/var/lib/postgresql/data/
                environment:
                        - POSTGRES_USER=${POSTGRES_USER_NAME}
                        - POSTGRES_DB=${POSTGRES_DB_NAME}
                        - POSTGRES_PASSWORD=${POSTGRES_USER_PASSWORD}
                ports:
                        - 5432:5432
        web:
                build: .
                env_file: ./.env
                command: sh -c "wait-for.sh db:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
                ports:
                        - "8000:8000"
                volumes:
                        - ./:/src/
                restart: on-failure
                depends_on:
                        - db
volumes:
        postgres_data:
