# Generated by Django 2.2.12 on 2020-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='uuidt',
            field=models.UUIDField(help_text='unique uuid Identity of the user', unique=True),
            preserve_default=False,
        ),
    ]
