# Generated by Django 2.2.12 on 2020-04-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userdetail_uuidt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='address',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='flat',
            field=models.CharField(default=807, help_text='flat number of the user', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='floor',
            field=models.CharField(default=8, help_text='Floor number of the user', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='society',
            field=models.CharField(default='Amrapali Silicon City', help_text='Society of the user', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='tower',
            field=models.CharField(default='C', help_text='Tower number/name of the user', max_length=10),
            preserve_default=False,
        ),
    ]
