# Generated by Django 2.2.12 on 2020-05-03 08:23

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200503_1322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
                ('objects', authentication.models.AuthUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
